/** @type {import('tailwindcss').Config} */
export default {
    content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
    theme: {
        fontFamily: {
            sans: [
                "system-ui",
                "-apple-system",
                "BlinkMacSystemFont",
                "Segoe UI",
                "Roboto",
                "Oxygen",
                "Ubuntu",
                "Cantarell",
                "Open Sans",
                "Helvetica Neue",
                "sans-serif",
                "Apple Color Emoji",
                "Segoe UI Emoji",
                "Segoe UI Symbol",
                "Noto Color Emoji",
            ],
            serif: ["ui-serif", "Georgia", "Cambria", "Times New Roman", "Times", "serif"],
            mono: [
                "JetBrainsMono Nerd Font",
                "JetBrains Mono",
                "FiraCode Nerd Font",
                "Fira Code",
                "SourceCodePro Nerd Font",
                "Source Code Pro",
                "CaskaydiaCove Nerd Font",
                "Cascadia Code",
                "Cascadia Mono",
                "Hack Nerd Font",
                "Hack",
                "IBMPlexMono Nerd Font",
                "IBM Plex Mono",
                "Menlo",
                "Monaco",
                "Ubuntu Mono",
                "Consolas",
                "ui-monospace",
                "SFMono-Regular",
                "Liberation Mono",
                "Courier New",
                "monospace",
            ],
        },
        extend: {
            colors: {
                accent: "var(--accent)",
                "primary-text": "var(--primary-text)",
                "secondary-text": "var(--secondary-text)",
                "blue-link": "var(--blue-link)",
                "primary-button-text": "var(--primary-button-text)",
                "primary-button-background": "var(--primary-button-background)",
                "primary-deemphasized-button-text": "var(--primary-deemphasized-button-text)",
                "primary-deemphasized-button-background": "var(--primary-deemphasized-button-background)",
                "secondary-button-text": "var(--secondary-button-text)",
                "secondary-button-background": "var(--secondary-button-background)",
                "web-wash": "var(--web-wash)",
                "comment-background": "var(--comment-background)",
                "card-background": "var(--card-background)",
                "hover-overlay": "var(--hover-overlay)",
                divider: "var(--divider)",
            },
            borderRadius: {
                "18px": "1.125rem",
            },
        },
    },
    plugins: [],
};
